# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-04-03 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DD_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='date',
            new_name='c_date',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='time',
            new_name='c_time',
        ),
        migrations.RemoveField(
            model_name='files',
            name='username',
        ),
    ]
